### ISSUE TITLE
fix! not close.

### ISSUE THREAD

**Issue by infinitylx** [oduvan/checkio-mission-frequency-sort#11]
assert list(frequency_sort([4, 6, 2, 2, 6, 4, 4, 4])) == [4, 4, 4, 4, 6, 6, 2, 2] <-- is incorrect order.

According to:

If two elements have the same frequency, they should end up in the same order as the first appearance in the list.
It should be:

 [4, 4, 4, 4, 6, 2, 2, 6]

**Comment by infinitylx** [comment]
yep one year ago this mistake was reported but looks like you don't care about fixing. 
I'm very disappointed.

**Comment by freemanlex** [comment]
They should end up in the same **order**, not exact view! 6 was earlier and we put **all** 6's together, then we put **all** 2's together. There is no mistake. During a whole year you should have been find out, how to solve it.
