### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by Celshade** [oduvan/checkio-mission-frequency-sort#2]
There is a blind spot in the tests. I was able to pass the mission without actually sorting the array in decreasing order. See my original code below, which passed the initial tests.
```
def frequency_sort(items: iter) -> list:
    """Sort an array of elements by frequency, in decreasing order.

    Args:
        items: An array of items.
    Returns:
        grouped: A sorted list of items.
    """
    grouped = []

    for item in items:
        if item in grouped:
            grouped.insert(grouped.index(item), item)
        else:
            grouped.append(item)
    return grouped
```
This should not have passed; because, thus far, all I had done was sort the array by equal values. This only passed due to the number of elements that are included in the test inputs and the sequence in which they're initially arranged. See below for one of the test examples currently in the mission.

`assert list(frequency_sort([4, 6, 2, 2, 6, 4, 4, 4])) == [4, 4, 4, 4, 6, 6, 2, 2]`

My code will pass the test [above] due to there being equal amounts of element 6 and element 2.
You can prove my code will fail by simply adding an additional 2 to the existing test. See below.

`assert list(frequency_sort([4, 6, 2, 2, 2, 6, 4, 4, 4])) == [4, 4, 4, 4, 2, 2, 2, 6, 6]`

My code would return `[4, 4, 4, 4, 6, 6, 2, 2, 2]` failing this new test, as it should.

I solved this [correctly] by simply altering my code to actually sort by element frequency; but, I will not post that here - due to anyone reading this who may have yet to solve the mission. I will make a PR for this issue. All in all, this is a good mission!

**Comment by oduvan** [comment]
thanks for support
