### ISSUE TITLE
Ошибочный тест

### ISSUE THREAD

**Issue by bespontoff** [oduvan/checkio-mission-frequency-sort#8]
https://github.com/CheckiO-Missions/checkio-mission-frequency-sort/blob/ff31e839e15963644f05dbd43cf0fa91b870f2d8/verification/tests.py#L14-L15

У шестерок и двоек одинаковая частота. Если два элемента имеют одинаковую частоту, они должны оказаться ***в том же порядке***, в котором стояли изначально в итераторе.
В тесте порядок нарушен.

Правильно будет 
`assert list(frequency_sort([4, 6, 2, 2, 6, 4, 4, 4])) == [4, 4, 4, 4, 6, 2, 2, 6]`

# Верный алгоритм
```python
def frequency_sort(items):
    # count frequency for each item
    counted_items = [(item, items.count(item)) for item in items]
    # sort by frequency
    sorted_items = sorted(counted_items, key=lambda item: item[1], reverse=True)

    return [item[0] for item in sorted_items]
```

**Comment by oduvan** [comment]
6 goes before 2 and numbers should be grouped

**Comment by infinitylx** [comment]
but in task there is nothing about grouping.

**Comment by oduvan** [comment]
The description will be improved, but the tests are correct.

@infinitylx 
> I'm very disappointed.

Sometimes, the tests (that are part of the mission description) fulfill the missing gaps in the text description. It is not best practice, but we are constantly working on improving the description.

You can help with sending a pull request with an improved description if you like.
